---
# Nginx コンテナのイメージを更新し、再作成・再起動する

- name: Pull latest Nginx image and recreate container
  community.docker.docker_compose_v2:
    project_src: "{{ deployment_paths.deployment_dir }}"
    files:
      - docker-compose.yml
    services:
      - "nginx"
    pull: always
    recreate: always
  environment:
    DOCKER_CONFIG: "/home/{{ app_user }}/.docker"
  become: yes
  tags:
    - docker
    - update-nginx-image

